config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  resources :projects
  resources :courses
  get 'blogs/index'
  resources :blogs
  # get 'welcome/index'

 root 'welcome#index'
 resources :students


 get '/test' => 'students#test'


 

namespace :admin do
    resources :students 
  end

  # scope module: :admin do
  #   resources :students
  # end
end






















   
#  resources :students do 
#   member do
#     get :personal_details  # member routes
#   end

#   collection do
#     get :active            # collection routes
#   end
# end



#  get "/about" => 'welcome#about'

#  get 'welcome/about'

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :student
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.eager_load(:student)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/index.html.erb
<div class="container">
    <h1><u>Listing Blogs</u></h1>

    <table class="table table-danger table-hover">
        <thead>
        <tr>
        <th>Title</th>
        <th>Student</th>
        <th colspan="4">Action</th>
        </tr>
        </thead>
        <tbody>
        <% @blogs.each do |blog| %>
        <tr>
            <td><%= blog.title %></td>
            <td><%= link_to blog.student.name_with_email,blog.student %></td>
            <td><%= link_to 'Show', blog, class: "btn btn-outline-success" %><td>
            <td><%= link_to 'Edit',edit_blog_path(blog), class: "btn btn-outline-warning me-2" %></td>
            <td><%= link_to 'Delete',blog,data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger" %></td>  
        </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/blogs/new.html.erb
<%= form_with model: @blog do |form| %>


    <div>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
    </div><br>
    
    <div>
    <%= form.label :content %><br>
    <%= form.text_field :content %>
    </div><br>


    <%= form.submit %>
<% end %> <br>
    <%= link_to "Back", blogs_path %> 