config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  resources :projects
  resources :courses
  get 'blogs/index'
  resources :blogs
  # get 'welcome/index'

 root 'welcome#index'
 resources :students


 get '/test' => 'students#test'


 

namespace :admin do
    resources :students 
  end

  # scope module: :admin do
  #   resources :students
  # end
end






















   
#  resources :students do 
#   member do
#     get :personal_details  # member routes
#   end

#   collection do
#     get :active            # collection routes
#   end
# end



#  get "/about" => 'welcome#about'

#  get 'welcome/about'

app/models/student.rb
class Student < ApplicationRecord
    paginates_per 7

    has_many :blogs
    has_and_belongs_to_many :courses

    has_many :student_projects
    has_many :projects, through: :student_projects
    
    # validates :age, numericality: true
    validates :first_name,:last_name,:email, presence: true
    validates :email,uniqueness: true
    validates :first_name,:last_name,length: {minimum: 2,maximum: 15}
    validates :first_name,:last_name,format: {with: /\A[a-zA-Z]+\z/,message: 'only letters are allowed'}
    
    # custom validates
    validate :validate_student_age


    after_commit  :display_student_age

    def display_student_age
        if self.date_of_birth.present?
            age = Date.today.year - self.date_of_birth.year
            puts "*********** Age of the Student is #{age} *************"
        else
            puts "************ Age can not calculated without date_of_birth ************* "
        end
    end

    def validate_student_age
        if self.date_of_birth.present?
            age = Date.today.year - self.date_of_birth.year
            if age < 15
                errors.add(:age, "please provide a valid date of birth here.Age must be greater than 15")
            end
        end
    end

    def full_name
        "#{first_name} #{last_name}"
    end

    def age_student
        if date_of_birth.present?
            Date.today.year - date_of_birth.year
        else
            nil
        end
    end

    def name_with_email
        "#{full_name} / #{email}"
    end
    
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
    before_action :set_students , only: %i[show edit update  destroy]
    before_action :authenticate_admin_user!
    # helper_method :formatted_date
 
    def index
        if params[:search].present?
            @students = Student.where("first_name LIKE ? OR email LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
        else
            @students = Student.all
        end    end
 
    def new
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)
        if @student.save 
            redirect_to admin_students_path , notice: "Student has been Created Successfully"
        else
            render :new, status: :unprocessable_entity

        end
    end
    

    def show 
    end  

    def edit
     
    end

    def update
        if @student.update(student_params)
            redirect_to admin_students_path , notice: "Student has been Updated Successfully"
        else
            render :new
        end
    end

    def destroy
        @student.destroy
        redirect_to admin_students_path , notice: "Student has been Deleted Successfully"
    end

    def test
    end

    private
    def student_params
        params.require(:student).permit(:first_name,:last_name,:email,:date_of_birth,:address,:contact)
    end

    def set_students
        @student = Student.find(params[:id])
    end

    # def formatted_date(date)
    #     date.strftime('%A %b  %d  %Y')
    # end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    # include ApplicationHelper
    before_action :set_students , only: %i[show edit update  destroy]
    # helper_method :formatted_date


    def index
        if params[:search].present?
            @students = Student.where("first_name LIKE ? OR email LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
        else
            @students = Student.all
        end
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)
        if @student.save 
            redirect_to students_path , notice: "Student has been Created Successfully"
        else
            render :new, status: :unprocessable_entity

        end
    end

    def show 
    end  

    def edit
     
    end

    def update
        if @student.update(student_params)
            redirect_to students_path , notice: "Student has been Updated Successfully"
        else
            render :new
        end
    end

    def destroy
        @student.destroy
        redirect_to students_path , notice: "Student has been Deleted Successfully"
    end

    def test
    end

    private
    def student_params
        params.require(:student).permit(:first_name,:last_name,:email,:date_of_birth,:address,:contact)
    end

    def set_students
        @student = Student.find(params[:id])
    end

    # def formatted_date(date)
    #     date.strftime('%A %b  %d  %Y')
    # end


end

app/helpers/students_helper.rb
module StudentsHelper
    
end

app/views/students/_form.html.erb
<div class="container pb-3" style="background-color:#d5f5f4; ">
    <%= form_with model: student do |form| %>
        <% if @student.errors.any? %>
            <% @student.errors.full_messages.each do |messages| %>
                <p><%= messages %></p>
            <%end%>
        <%end%>

        <div class:"form-group mb-3">
        <%= form.label :first_name %> <br>
        <%= form.text_field :first_name ,class:"form-control" %>
        </div><br>
        
        <div class:"form-group">
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name,class:"form-control" %>
        </div><br>
        
        <div class:"form-group">
        <%= form.label :email %><br>
        <%= form.text_field :email,class:"form-control" %>
        </div><br>

        <div class:"form-group">
        <%= form.label :date_of_birth %><br>
        <%= form.date_field :date_of_birth,class:"form-control" %>
        </div><br>

        <div class:"form-group">
        <%= form.label :contact %><br>
        <%= form.text_field :contact,class:"form-control" %>
        </div><br>

        <div class:"form-group">
        <%= form.label :address %><br>
        <%= form.text_field :address,class:"form-control" %>
        </div><br>

        <div>
        <%= form.submit class: "btn btn-dark me-2" %>  <%= link_to "Back", students_path ,class: "btn btn-dark" %> 
        </div>
        <% end %> 
        
</div>

app/views/students/edit.html.erb
<div class="container">
    <strong class:"text-info bg-dark"><%= notice %></strong>

    <h1><u>Edit Student</u></h1>

    <%= render "form" , student: @student %>
</div>

app/views/students/index.html copy.erb
<div class="container">
    <p class="text-info bg-dark"><%= notice %></p>

    <h1><u>Listing Students</u></h1>

    <table class="table table-danger table-hover">
        <thead>
        <tr>
        <th>Student</th>
        <th>Date of Birth</th>
        <th>Contact</th>
        <th>Address</th>
        <th colspan="4">Action</th>
        </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
        <tr>
            <td><%= student.name_with_email %></td>
            <td><%= student.date_of_birth %></td>
            <td><%= student.contact %></td>
            <td><%= student.address %></td>

            <td><%= link_to 'Show', student, class: "btn btn-outline-success" %><td>
            <td><%= link_to 'Edit',edit_student_path(student), class: "btn btn-outline-warning me-2" %></td>
            <td><%= button_to 'Destroy',student, method: :delete, onclick: "return confirm{'Are you sure?'}",class:"btn btn-outline-danger" %></td>  
        </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/students/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/students">Student List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/students/new">New Student</a>
            <li class="nav-item">
            <a class="nav-link" href="/">welcome</a>
        </ul>
    
        <% if admin_user_signed_in? %>
          <%= button_to 'Sign-Out',
          destroy_admin_user_session_path, method: :delete, :onclick => "return confirm('Are you sure ?')",
          class: "btn btn-outline-info" %>
        <% else %>
        <%= button_to 'Sign-In',new_admin_user_session_path, class: "btn btn-outline-info" %>
        
        <% end %>    
      </div>
    </div>
  </nav>
<div class="container my-4">
  <%= form_tag(students_path, :method => "get",   
  class: 'navbar-form navbar-left') do %>  
      <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control me-2" %>  
          <div class="input-group-btn">  
              <%= button_tag "Search", :class => 'btn btn-primary glyphicon glyphicon-search',:name => nil  %>  
          </div> 
      </div>  
  <% end %>
</div>
<div class="container">
    <p class="text-info bg-dark my-2"><%= notice %></p>
    <h1><u>Listing Students</u></h1>

    <table class="table table-info table-hover">
        <thead>
        <tr>
        <th>First Name </th>
        <th>Last Name </th>
        <th>Email</th>
        <th>Date of Birth</th>
        <th>Contact</th>
        <th>Address</th>
        <th colspan="4">Action</th>
        </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
        <tr>
            <td><%= student.first_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.email %></td>
            <td><%= student.date_of_birth %></td>
            <td><%= student.contact %></td>
            <td><%= student.address %></td>

            <td><%= link_to 'Show', student, class: "btn btn-outline-success" %><td>
            <td><%= link_to 'Edit',edit_student_path(student), class: "btn btn-outline-warning me-2" %></td>
            <td><%= button_to 'Destroy',student, method: :delete, onclick: "return confirm{'Are you sure?'}",class:"btn btn-outline-danger" %></td>  
        </tr>
        <% end %>
        </tbody>
    </table>
</div>
<div class="bg-white border">
    
      <section class="p-4 text-center">
        <footer class="bg-dark text-center text-white">
          <!-- Grid container -->
          <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
              <!-- Facebook -->
              <a class="btn text-white btn-floating m-1" style="background-color: #3b5998;" href="https://www.facebook.com/home.php" role="button"><i class="bi bi-facebook"></i></a>

              <!-- Twitter -->
              <a class="btn text-white btn-floating m-1" style="background-color: #55acee;" href="#!" role="button"><i class="bi bi-twitter"></i></a>

              <!-- Google -->
              <a class="btn text-white btn-floating m-1" style="background-color: #dd4b39;" href="https://www.google.com/" role="button"><i class="bi bi-google"></i></a>

              <!-- Instagram -->
              <a class="btn text-white btn-floating m-1" style="background-color: #ac2bac;" href="https://www.instagram.com/" role="button"><i class="bi bi-instagram"></i></a>

              <!-- Linkedin -->
              <a class="btn text-white btn-floating m-1" style="background-color: #0082ca;" href="https://www.linkedin.com/feed/" role="button"><i class="bi bi-linkedin"></i></a>
              <!-- Github -->
              <a class="btn text-white btn-floating m-1" style="background-color: #333333;" href="https://github.com/TUSHARJAITWAL" role="button"><i class="bi bi-github"></i></a>
            </section>
            <!-- Section: Social media -->
          </div>
          <!-- Grid container -->

          <!-- Copyright -->
          <div class="text-center p-3" style="background-color:pink;">
            <a class="text-white" href="https://tusharjaitwal.github.io/my-profile.github.io/">Jaitwal.com</a>
          </div>
          <!-- Copyright -->
        </footer>
      </section>
          
  </div>

app/views/students/new.html.erb
<div class="container">
    <h1><u>New Students</u></h1>

    <%= render  "form", student: @student %>
</div>

app/views/students/show.html.erb
<div class="card mb-3 my-4" style="max-width: 800px; margin-left:300px; background-color:#d5f5f4;">
  <div class="row g-0 py-5">
    <div class="col-md-4">
      <img src="https://static.thenounproject.com/png/2410970-200.png" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <h5 class="card-title"><strong>Name :--</strong><%= @student.full_name %></h5>
        <p class="card-text"><strong>Email      : -- </strong><%= @student.email %></p>
        <p class="card-text"><strong>DOB :- </strong><%= @student.date_of_birth.strftime('%a %b %d %Y') %></p>
        <p class="card-text"><strong>Age     : -- </strong><%= @student.age_student %></p>
        <p class="card-text"><strong>Contact      : -- </strong><%= @student.contact %></p>
        <p class="card-text"><strong>Address      : -- </strong><%= @student.address %></p>

        <a><%= link_to 'Back', students_path, class: "btn btn-outline-danger me-3" %></a>
        <a><%= link_to 'Edit', edit_student_path, class: "btn btn-outline-danger" %></a>
        </div>
    </div>
  </div>
</div>